### ISSUE TITLE
Search index seems to be missing content

### ISSUE THREAD

**Issue by hwillson** [apollographql/gatsby-theme-apollo#22] opened 2019-03-26 14:34 UTC
It looks like a fair amount of the docs content isn't being indexed / made searchable by Algolia:

![Screenshot 2019-03-26 10 12 21](https://user-images.githubusercontent.com/137740/55005595-a9059880-4fb2-11e9-9427-eab9d87e388a.png)

**Comment by trevorblades** [comment] 2019-03-26 21:45
Good catch, @hwillson! As @abernix mentioned in Slack, this is likely due to Algolia missing the element classes that it looks for, as configured here: https://github.com/algolia/docsearch-configs/blob/master/configs/apollodata.json

I added all of the necessary classes in 269852c347243439cd1108822c26cbcb894f97a3, and I'll deploy this along with a few other changes later today.

**Comment by hwillson** [comment] 2019-03-26 22:29
Great, thanks @trevorblades!

**Comment by trevorblades** [comment] 2019-03-28 22:43
Fixed by 269852c347243439cd1108822c26cbcb894f97a3 and 5ec376f034b766ae8322c41dfdaef413213a6e18

**Closed by trevorblades** 2019-03-28 22:43 UTC

**Comment by abernix** [comment] 2019-03-29 09:13
Thanks, @trevorblades.  It might be worth leaving a comment in the code noting their importance, to avoid a regression in the future?
